version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app
    overwrite: yes
hooks:
  BeforeInstall:
  BeforeInstall:
    - location: scripts/cleanup_old_deployment.sh
      timeout: 300
      runas: root
    - location: scripts/stop_old_container.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_new_container.sh
      timeout: 300
      runas: root
